### ISSUE TITLE
Please Alphabetize the List

### ISSUE THREAD

**Issue by BeaconSlash** [maiuswong/simaware-tracon-project#24]
Let's have some semblance of organization and alphabetize the list by facility identifier or something reasonable logical.

**Comment by collink2451** [comment]
I believe it should be organized by ARTCC/FIR then alphabetized within the facility.
The ZBW facilities are organized alphabetically by prefix and I would like to leave it that way.

**Comment by BeaconSlash** [comment]
Actually, even better... use a 6 letter standard, 3 letters for parent ARTCC/FIR, then 3 character facility ID.

**Comment by BeaconSlash** [comment]
> I believe it should be organized by ARTCC/FIR then alphabetized within the facility. The ZBW facilities are organized alphabetically by prefix and I would like to leave it that way.

I think I was typing the same time as you!

**Comment by collink2451** [comment]
> Actually, even better... use a 6 letter standard, 3 letters for parent ARTCC/FIR, then 3 character facility ID.
> 
> Like ZAUALO ZAUAZO

Are you referring to setting the id variable to include the ARTCC/FIR?
If so, the id variable is what is displayed above the Tracon as a label and I don't think it should contain the ARTCC.

**Comment by BeaconSlash** [comment]
There should be a way to organize this data internally. I'm not advocating for the Simaware public site to say "ZAUALO", but perhaps each line in here ought to have another field simply to organize the data so parent facilities can more easily find their batch to edit.

**Comment by maiuswong** [comment]
if we want to add "facility" to each line as an unused property before the "id", i could just sort them alphabetically every now and then.

**Comment by jannikvogel** [comment]
> Actually, even better... use a 6 letter standard, 3 letters for parent ARTCC/FIR, then 3 character facility ID.
> 
> Like ZAUALO ZAUAZO
> 
> etc. etc.

Not really european friendly as our FIRs and Identifiers are containing four letters each xD

**Comment by mixMugz** [comment]
I can do this.

https://github.com/maiuswong/simaware-tracon-project/issues/117
