### ISSUE TITLE
Problem With CDG 

### ISSUE THREAD

**Issue by Iwhite67** [maiuswong/simaware-tracon-project#76]
Hello, i have pull request the coord for CDG App, but i have a problem into, i don't see what is the error

![image](https://user-images.githubusercontent.com/9698964/156829509-3eeaea1c-7199-4b47-80fc-757af5897af1.png)

**Comment by Iwhite67** [comment]
this is the problem ? https://github.com/maiuswong/simaware-tracon-project/pull/77

**Comment by maiuswong** [comment]
issue seems to be resolved
